version: "3.9"

services:
  backend:
    build: ./apps/api
    container_name: desafio-mb-backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: always

  frontend:
    build: ./apps/ui
    container_name: desafio-mb-rontend
    ports:
      - "8080:80"
    environment:
      NODE_ENV: production
    restart: always
    depends_on:
      - backend

  storybook:
    build:
      context: ./apps/ui
      dockerfile: Dockerfile.storybook
    container_name: desafio-mb-storybook
    ports:
      - "6006:6006"
    environment:
      NODE_ENV: development
    restart: unless-stopped
    depends_on:
      - frontend
