version: "3.9"

services:
  backend:
    build: ./apps/api
    container_name: desafio-backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: always
    volumes:
      - ./apps/ui/dist:/app/ui/dist

  frontend:
    build: ./apps/ui
    container_name: desafio-frontend
    ports:
      - "8080:80"
    environment:
      NODE_ENV: production
    restart: always
    volumes:
      - ./apps/ui/dist:/app/ui/dist
